# Generated by Django 5.1.11 on 2025-07-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_delete_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
